[theme]
base = "light"                         # Modo claro
primaryColor = "#020873"              # Azul oscuro (para sliders, radio points, hovers)
secondaryBackgroundColor = "#FFFFFF"  # Fondo secundario sidebar
textColor = "#000000"                 # Texto negro
font = "sans serif"                   # Fuente sin serifas
